# Generated by Django 4.1.2 on 2022-10-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite_posts',
            field=models.ManyToManyField(help_text='List of favorited posts', related_name='favorite_posts', through='core.AuthorFavoritePosts', to='core.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='Comment object which this comment replied to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='header_img',
            field=models.ImageField(blank=True, help_text='Image to be placed at the top of blog post', null=True, upload_to='post_headers/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_author',
            field=models.ForeignKey(help_text='The author of post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorLikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this entry created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was this entry updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_liked_posts', to='core.author')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='core.posts')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='liked_posts',
            field=models.ManyToManyField(help_text='List of liked posts', related_name='liked_posts', through='core.AuthorLikedPosts', to='core.posts'),
        ),
    ]
